App/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import IndexMain
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('',IndexMain.as_view(), name='home'),
    # re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # re_path(r'^staticfiles/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import Index, Write, Detail, Delete, Update, CommentWrite, CommentDelete, Search, ImgUpload, LoadPost, CategorySearch, Likepost

app_name = 'blog'

urlpatterns = [
    path('', Index.as_view() , name='list'),
    # post
    path('write/', Write.as_view() , name='write'),
    path('<int:pk>/', Detail.as_view() , name='detail'),
    path('edit/<int:pk>/', Update.as_view() , name='edit'),
    path('loadpost/<int:pk>/', LoadPost.as_view() , name='load'),
    path('delete/<int:pk>/', Delete.as_view() , name='delete'),
    path('search/', Search.as_view() , name='search'),
    path('categorysearch/', CategorySearch.as_view() , name='category'),
    path('imageupload/', ImgUpload.as_view() , name='img-upload'),
    path('like/<int:pk>/', Likepost.as_view() , name='like'),
    # comment
    path('comment/write/<int:pk>/', CommentWrite.as_view() , name='cm-write'),
    path('comment/delete/<int:pk>/', CommentDelete.as_view() , name='cm-delete'),

]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(default='active', max_length=20)
    thumbnail = models.ImageField(upload_to='blog/media',null=True,blank=True)
    views = models.IntegerField(default=0)
    like = models.JSONField(default=dict,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

class Category(models.Model):
    post = models.OneToOneField("Post", on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(default='active', max_length=20)


class Comment(models.Model):
    
    post = models.ForeignKey(Post, on_delete=models.CASCADE) 
    content = models.CharField(max_length=30)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(default='active', max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'Comment on {self.post.title}'
    
### 이미지 업로드 모델
class ImageUpload(models.Model):
    image = models.ImageField(upload_to='blog/media',null=True)
    created_at = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms
from .models import Post, Comment

# Form: html에 있는 form 태그
# Model Form: model을 사용하는 form
# 유효성 검사를 위해서 이렇게 사용함
class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'thumbnail', 'content']
        

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.TextInput(attrs={'placeholder': 'Input Any Comments ...'})
        }

blog/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse 
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, F
from .models import Post, Comment, ImageUpload, Category
from .forms import PostForm, CommentForm

### Post
class Index(View):
    def get(self, request):
        post_objs = Post.objects.all().filter(status='active').order_by('-created_at')
        categories = Category.objects.filter(status='active').values('name').annotate(count=Count('name'),category=F('name')).values('count', 'category')
        context = {
            "posts": post_objs,
            "categories": categories,
        }
        return render(request, 'blog/post_list.html', context)


class Write(LoginRequiredMixin, View):
    Mixin : LoginRequiredMixin
    login_url = '/user/login'
    redirect_field_name = 'next'
    
    def get(self, request):
            
        form = PostForm()
        context = {
            'form': form
        }
        return render(request,'blog/post_write.html',context)
    
    def post(self, request):

        user = request.user
        title = request.POST['title']
        content = request.POST['content']
        thumbnail = request.POST['thumbnail']
        category = request.POST['category']
        
        if thumbnail != "blank":
            post = Post.objects.create(title=title, content=content, writer=user,thumbnail=thumbnail)
        else:
            post = Post.objects.create(title=title, content=content, writer=user)
        category = Category.objects.create(post=post,name=category)
        
        # serializer = PostSerializer(post)
        data = {
            'message': '저장이 완료되었습니다.'
        }
        return JsonResponse(data)


class Detail(View):
    def get(self, request, pk):
        try:
            post = Post.objects.get(pk=pk)
        except:
            return render(request,'blog/nonexistent.html')
        else:
            if post.status == 'active':
                post.views = post.views + 1
                post.save()
                
                comments = Comment.objects.filter(post=post,status='active')
                comment_form = CommentForm()
                
                context = {
                    'post': post,
                    'comments': comments,
                    'comment_form': comment_form,
                }
            
                return render(request,'blog/post_view.html', context)
        
            return render(request,'blog/nonexistent.html')


class Update(LoginRequiredMixin, View):
    Mixin : LoginRequiredMixin
    login_url = '/user/login'
    redirect_field_name = 'next'
    
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        if post.writer == request.user:
            return render(request, 'blog/post_edit.html')
        return redirect('blog:list', pk=pk)
    
    def post(self, request, pk):
        
        post = Post.objects.get(pk=pk)
        category = Category.objects.get(post=post)
        
        post.title = request.POST['title']
        post.content = request.POST['content']
        thumbnail = request.POST['thumbnail']
        category.name = request.POST['category']
        
        if thumbnail != "blank":
            post.thumbnail = thumbnail
            
        post.save()
        category.save()
        # serializer = PostSerializer(post)
        data = {
            'message': '수정이 완료되었습니다.'
        }
        return JsonResponse(data)


class LoadPost(View):
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        data = {
            'title': post.title,
            'content': post.content,
            'category': post.category.name,
            'thumbnail': str(post.thumbnail)
        }
        return JsonResponse(data)


class Delete(View):
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        
        if post.writer != request.user:
            return redirect('blog:list')
        category = Category.objects.get(post=post)
        
        post.status = 'delete'
        category.status = 'delete'
        
        category.save()
        post.save()
        return redirect('blog:list')


class Likepost(View):
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        if request.user.is_authenticated:
            like_user = str(request.user.pk)
            try:
                valid = post.like[like_user]
            except:
                post.like[like_user] = 'like'
            else:
                if  valid == 'like':
                    post.like[like_user] = 'Disabled'
                else:
                    post.like[like_user] = 'like'
            post.save()
            data = {
                'message': 'success'
            }
            return JsonResponse(data)
        data = {
                'message': 'Login Please'
            }
        return JsonResponse(data)


class ImgUpload(View):
    def post(self, request):
        image = request.FILES['image']
        imageUpload = ImageUpload.objects.create(image=image)
        url = imageUpload.image
        data = {
            'url': str(url)
        }
        return JsonResponse(data)


class Search(View):
    def get(self, request):
        post_objs = Post.objects.filter(status='active',title__contains=request.GET['keyword']).order_by('-created_at')
        categories = Category.objects.filter(status='active').values('name').annotate(count=Count('name'),category=F('name')).values('count', 'category')
        context = {
            "posts": post_objs,
            "categories": categories,
            "keyword": request.GET['keyword']
        }
        return render(request, 'blog/post_search.html', context)


class CategorySearch(View):
    def get(self, request):
        
        # print(results.query) SQL 쿼리문을 볼 수 있다.
        results = Category.objects.select_related().filter(name=request.GET['category'],status='active').order_by('-created_at')
        categories = Category.objects.filter(status='active').values('name').annotate(count=Count('name'),category=F('name')).values('count', 'category')
        context = {
            "results": results,
            "categories": categories,
            "keyword": request.GET['category']
        }
        return render(request, 'blog/post_category.html', context)

### Comment
class CommentWrite(LoginRequiredMixin, View):
    Mixin : LoginRequiredMixin
    login_url = '/user/login'
    redirect_field_name = 'next'
    
    def post(self, request, pk):
        form = CommentForm(request.POST)
        post = Post.objects.get(pk=pk)
        
        if form.is_valid():
            
            content = form.cleaned_data['content']    
            writer = request.user
            comment = Comment.objects.create(post=post, content=content, writer=writer)
            
            return redirect('blog:detail', pk=pk)
        
        form.add_error(None,'폼이 유효하지 않습니다.')
        context = {
            'post': post,
            'comments': post.comment_set.all(),
            'comment_form': form,
        }
        
        return render(request, 'blog/post_detail.html', context)
    
    
class CommentDelete(View):
    def post(self, request, pk):
        
        comment = Comment.objects.get(pk=pk)
        
        if request.user != comment.writer:
            return render(request,'blog/error.html')
        
        post_id = comment.post.id
        comment.status = 'delete'
        comment.save()
    
        return redirect('blog:detail', pk=post_id)
    
        
    

blog/templates/blog/error.html
<!DOCTYPE html>
<html lang="ko">
    {% load static %}
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Error</title>
    </head>
    <body>
        <main class="container">
            <h1>존재하지 않는 게시물입니다.</h1>
        </main>
    </body>
</html>
   

blog/templates/blog/nonexistent.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
	<div class="view">
		<div class="max-width">
			<section class="wrap-box">
				<div class="inner">
                    <h3>삭제되었거나 존재하지 않는 게시물입니다.</h3>
                </div>
			</section>
		</div>
	</div>
{% endblock %}

blog/templates/blog/post_category.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
    <!-- main -->
    <main>
        <!-- posts -->
        <div class="max-width">
            <h2 class="a11y-hidden">Post</h2>
            <section class='first_section'>
                <h3>😁 Profile</h3>
                {% if request.user.is_authenticated %}
                    <aside class="about">
                        {% if request.user.profile.avatarUrl %}
                            <img src="{{request.user.profile.avatarUrl.url}}" alt="" class="user-profile" />
                        {% else %}
                            <img src="{%static 'user/image/basic_profile.jpg'%}" alt="" class="user-profile" />
                        {% endif %}
                        <p class="user-name">{{request.user.profile.name}}</p>
                        <p class="user-description">{{request.user.profile.aboutMe}}
                    </aside>
                {% else %}
                    <aside class="about">
                        <img src="{%static 'user/image/basic_profile.jpg'%}" alt="" class="user-profile" />
                        <p class="user-name">User Name</p>
                        <p class="user-description">Please Login :)</p>
                    </aside>
                {% endif %}
                <h3>💻 Repo</h3>
                <aside class="about">
                    <ul class="sns">
                        <li>
                            <a href="https://github.com/Hyunwooz/Django-blog">
                                <img src="{% static 'blog//assets/Github.svg' %}" alt="GitHub" /> GitHub
                            </a>
                        </li>
                    </ul>
                </aside>
                <h3>📱 Contact</h3>
                <aside class="about">
                    <ul class="sns">
                        <li>
                            <a href="#">
                                <img src="{% static 'blog/assets/Facebook.svg' %}" alt="Facebook" /> Facebook
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{% static 'blog/assets/Twitter.svg' %}" alt="Twitter" /> Twitter
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{% static 'blog/assets/Instagram.svg' %}" alt="Instagram" /> Instagram
                            </a>
                        </li>
                    </ul>
                </aside>
            </section>
            <section class='second_section'>
                <h3>🔎 search</h3>
                <div class="header-search">
                    <form action="{% url 'blog:search' %}" method="get">
                        <input class='header-search__text' placeholder="Search by title" ,type="text" , name="keyword" , required>
                        <button class='header-search__btn' type='submit'><i class="fa-solid fa-magnifying-glass"></i></button>
                    </form>
                </div>
                <h3>🧷 Posts</h3>
                <h4>"{{ keyword }}" 카테고리 모음입니다.</h4>
                {% if results %}
                <ul class="posts">
                    {% for result in results %}
                    <li>
                        <a href="{% url 'blog:detail' pk=result.post.pk %}" class="post">
                            <article>
                                {% if result.post.thumbnail %}
                                    <div class="img-wrap" style="background-image: url({{ result.post.thumbnail }}); background-size: cover; background-position: center;">
                                    </div>
                                {% endif %}
                                <div class="contents-wrap">
                                    <h3>{{result.post.title}}</h3>
                                    <!-- author -->
                                    <dl class="author-wrap">
                                        <dt class="a11y-hidden">Author</dt>
                                        <dd class="author">
                                            {% if result.post.writer.profile.avatarUrl.url %}
                                                <img src="{{result.post.writer.profile.avatarUrl.url}}" alt="" />
                                            {% else %}
                                                <img src="{%static 'user/image/basic_profile.jpg'%}" alt="" />
                                            {% endif %}
                                            {{ result.post.writer.profile.name }}
                                        </dd>
                                        <dt class="a11y-hidden">Created</dt>
                                        <dd class="created">{{result.post.created_at}}</dd>
                                        <dt class="a11y-hidden">views</dt>
                                        <dd class="views">Views : {{result.post.views}}</dd>
                                    </dl>
                                    <!-- //author -->
                                    <!-- category -->
                                    <dl class="category">
                                        <dt class="a11y-hidden">Category</dt>
                                        <dd>{{ result.name }}</dd>
                                    </dl>
                                    <!-- //category -->
                                </div>
                            </article>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
                {% else %}
                    <p class="nonexistent">작성된 게시물이 없습니다.</p>
                {% endif %}
            </section>
            <!-- //posts -->
            <!-- about -->
            <section class='third_section'>
                <h3>🎫 Category</h3>
                    <aside class="about">
                        <ul class="categories">
                            <li>
                                <form action="{% url 'blog:list' %}" method="get">
                                    <button class='category_search' type='submit'>All</button>
                                </form>
                            </li>
                            {% for category in categories %}
                            <li>
                                <form action="{% url 'blog:category' %}" method="get">
                                    <input type="hidden", value="{{category.category}}", name="category">
                                    <button class='category_search' type='submit'>{{category.category}} ({{category.count}})</button>
                                </form>
                            </li>
                            {% endfor %}
                        </ul>
                    </aside>
            </section>
            <!--//about -->
        </div>
    </main>
    
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %} 
{% load static %}
{% load getValue %}

{% block content %}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <!-- main -->
    <main>
        <!-- posts -->
        <div class="max-width">
            <h2 class="a11y-hidden">Post</h2>
            <section class='first_section'>
                <h3>😁 Profile</h3>
                {% if request.user.is_authenticated %}
                    <aside class="about">
                        {% if request.user.profile.avatarUrl %}
                            <img src="{{request.user.profile.avatarUrl.url}}" alt="" class="user-profile" />
                        {% else %}
                            <img src="{%static 'user/image/basic_profile.jpg'%}" alt="" class="user-profile" />
                        {% endif %}
                        <p class="user-name">{{request.user.profile.name}}</p>
                        <p class="user-description">{{request.user.profile.aboutMe}}
                    </aside>
                {% else %}
                    <aside class="about">
                        <img src="{%static 'user/image/basic_profile.jpg'%}" alt="" class="user-profile" />
                        <p class="user-name">User Name</p>
                        <p class="user-description">Please Login :)</p>
                    </aside>
                {% endif %}
                <h3>💻 Repo</h3>
                <aside class="about">
                    <ul class="sns">
                        <li>
                            <a href="https://github.com/Hyunwooz/Django-blog">
                                <img src="{% static 'blog//assets/Github.svg' %}" alt="GitHub" /> GitHub
                            </a>
                        </li>
                    </ul>
                </aside>
                <h3>📱 Contact</h3>
                <aside class="about">
                    <ul class="sns">
                        <li>
                            <a href="#">
                                <img src="{% static 'blog/assets/Facebook.svg' %}" alt="Facebook" /> Facebook
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{% static 'blog/assets/Twitter.svg' %}" alt="Twitter" /> Twitter
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{% static 'blog/assets/Instagram.svg' %}" alt="Instagram" /> Instagram
                            </a>
                        </li>
                    </ul>
                </aside>
            </section>
            <section class='second_section'>
                <h3>🔎 search</h3>
                <div class="header-search">
                    <form action="{% url 'blog:search' %}" method="get">
                        <input class='header-search__text' placeholder="Search by title" ,type="text" , name="keyword" , required>
                        <button class='header-search__btn' type='submit'><i class="fa-solid fa-magnifying-glass"></i></button>
                    </form>
                </div>
                <h3>🧷 Posts</h3>
                {% if posts %}
                <ul class="posts">
                    {% for post in posts %}
                    <li>
                        <a href="{% url 'blog:detail' pk=post.pk %}" class="post">
                            <article>
                                {% if post.thumbnail %}
                                    <div class="img-wrap" style="background-image: url({{ post.thumbnail }}); background-size: cover; background-position: center;">
                                    </div>
                                {% endif %}
                                <div class="contents-wrap">
                                    <h3>{{post.title}}</h3>
                                    <!-- author -->
                                    <dl class="author-wrap">
                                        <dt class="a11y-hidden">Author</dt>
                                        <dd class="author">
                                            {% if post.writer.profile.avatarUrl.url %}
                                                <img src="{{post.writer.profile.avatarUrl.url}}" alt="" />
                                            {% else %}
                                                <img src="{%static 'user/image/basic_profile.jpg'%}" alt="" />
                                            {% endif %}
                                            {{ post.writer.profile.name }}
                                        </dd>
                                        <dt class="a11y-hidden">Created</dt>
                                        <dd class="created">{{post.created_at}}</dd>
                                        <dt class="a11y-hidden">views</dt>
                                        <dd class="views">Views : {{post.views}}</dd>
                                        {% if request.user.is_authenticated%}
                                        {% with like_user=request.user.pk %}
                                            <dd>
                                                <form class="post_like_form" >
                                                    <button class='post_like_btn' id="{{post.pk}}" type='submit'>
                                                        {% if post.like|get_item:like_user == 'like'%}
                                                            <i class="fa-solid fa-heart"></i>
                                                        {% else %}
                                                            <i class="fa-regular fa-heart"></i>
                                                        {% endif %}
                                                    </button>
                                                </form>
                                            </dd>
                                        {% endwith %}
                                        {% endif %}
                                    </dl>
                                    <!-- //author -->
                                    <!-- category -->
                                    <dl class="category">
                                        <dt class="a11y-hidden">Category</dt>
                                        <dd>{{ post.category.name }}</dd>
                                    </dl>
                                    <!-- //category -->
                                </div>
                            </article>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
                {% else %}
                    <p class="nonexistent">작성된 게시물이 없습니다.</p>
                {% endif %}
            </section>
            <!-- //posts -->
            <!-- about -->
            <section class='third_section'>
                <h3>🎫 Category</h3>
                    <aside class="about">
                        <ul class="categories">
                            <li>
                                <form action="{% url 'blog:list' %}" method="get">
                                    <button class='category_search' type='submit'>All</button>
                                </form>
                            </li>
                            {% for category in categories %}
                                <li>
                                    <form action="{% url 'blog:category' %}" method="get">
                                        <input type="hidden", value="{{category.category}}", name="category">
                                        <button class='category_search' type='submit'>{{category.category}} ({{category.count}})</button>
                                    </form>
                                </li>
                            {% endfor %}
                        </ul>
                    </aside>
            </section>
            <!--//about -->
        </div>
    </main>
    <script src="{% static 'blog/js/utils.js' %}" type="module"></script>
    <script src="{% static 'blog/js/like.js' %}" type="module"></script>
{% endblock %}

blog/templates/blog/post_view.html
{% extends 'base.html' %} 
{% load static %}
{% load getValue %}

{% block content %}
	<div class="view">
		<div class="max-width">
			<section class="wrap-box">
				<div class="inner">
					{% if post.thumbnail %}
						<div class="img-wrap" style="background-image: url({{ post.thumbnail }}); background-size: cover; background-position: center;">
						</div>
					{% endif %}
					<div class="title-wrap">
						<h2>{{ post.title }}</h2>
					</div>
					<!-- author -->
					<dl class="author-wrap">
						<dt class="a11y-hidden">Author</dt>
						<dd class="author">
							{% if post.writer.profile.avatarUrl.url %}
								<img src="{{ post.writer.profile.avatarUrl.url }}" alt="" />
							{% else %}
								<img src="{%static 'user/image/basic_profile.jpg'%}" alt=""/>
							{% endif %}
							{{ post.writer.name }}
						</dd>
						<dt class="a11y-hidden">Created</dt>
						<dd class="created">{{ post.created_at }}</dd>
						<dt class="a11y-hidden">Views</dt>
						<dd class="views">조회수 : {{ post.views }}</dd>
					</dl>
					<!-- //author -->
					<!-- category -->
					<dl class="category">
						<dt class="a11y-hidden">Category</dt>
						<dd>{{ post.category.name }}</dd>
					</dl>
					<hr />
					<!-- //category -->
					<div class="view-contents">
						{{ post.content | safe }}
					</div>
					<hr />
					<!-- 댓글 작성 화면 -->
					<h3 class='comment_title'>Comments</h3>
					{% if request.user.is_authenticated %}
					<form class='comment_input' style="display: flex; align-items: center;" action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
						{% if request.user.profile.avatarUrl %}
                            <img src="{{request.user.profile.avatarUrl.url}}" alt="" class="loginuser_avatar" />
                        {% else %}
                            <img src="{%static 'user/image/basic_profile.jpg'%}" alt="" class="loginuser_avatar" />
                        {% endif %}
						{% csrf_token %}
						{{ comment_form.content }}
						<button calss="comment-submit" type="submit" value=""><i class="fa-solid fa-paper-plane"></i></button>
					</form>
					{% endif %}
					<!-- 댓글 출력 화면 -->
					<ul class='post_comments'>
						{% if comments %}
						{% for comment in comments %}
							<li class='post_comment'>
								<img class='comment_writer_avatar' src={{comment.writer.profile.avatarUrl.url}}></img>
								<div class='comment_writer_info'>
									<p class='comment_writer_name'>{{ comment.writer.profile.name }}</p>
									<p class='comment_writer_content'>{{ comment.content }}</p>
								</div>
								{% if request.user == comment.writer %}
								<form class='comment_writer_delete' action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
									{% csrf_token %}
									<input type="submit" class="btn-delete" value=""></input>
								</form>
								{% endif %}
							</li>
						{% endfor %}
						{% else %}
							<li>댓글이 없습니다.</li>
						{% endif %}
					</ul>
					{% if request.user == post.writer %}
						<div class="btn-group">
							<a href="{% url 'blog:edit' pk=post.pk %}" class="btn-modify">
								<span class="a11y-hidden">modify</span>
							</a>
							<form action="{% url 'blog:delete' pk=post.pk %}" method="post">
								{% csrf_token %}
								<button type="submit" class="btn-delete">
									<span class="a11y-hidden">delete</span>
								</button>
							</form>
							
						</div>
						
					{% endif %}
					
					<a href="{% url 'blog:list' %}" class="btn-back">
						<span class="a11y-hidden">Back</span>
					</a>
			</section>
		</div>
	</div>
{% endblock %}