App/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import IndexMain
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('',IndexMain.as_view(), name='home'),
    # re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # re_path(r'^staticfiles/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import Join, Login, Logout, ProfileUpdate, ChangePassWord

app_name = 'user'

urlpatterns = [
    path("join/", Join.as_view(), name='join'),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name='logout'),
    path("changePassword/", ChangePassWord.as_view(), name='change-pw'),
    path("profile/edit/", ProfileUpdate.as_view(), name='pf-edit'),
] 

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils import timezone

class UserManager(BaseUserManager):
    
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError('User must have an email')
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    # create_user
    def create_user(self, email, password, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)
    # create_superuser
    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, max_length=255)
    is_profile = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True, null=True, blank=True)
    
    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = UserManager()


class Profile(models.Model):
    user = models.OneToOneField('User', on_delete=models.CASCADE)
    name = models.CharField(default='닉네임', max_length=50, null=True, blank=True)
    avatarUrl = models.ImageField(upload_to='user/media',null=True,blank=True)
    aboutMe = models.TextField(default='자신을 소개해주세요 :)',null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import Profile

User = get_user_model()

class JoinForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['email']

    def __init__(self, *args, **kwargs):
        super(JoinForm, self).__init__(*args, **kwargs)

        for fieldname in ['email', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

class LoginForm(AuthenticationForm):
    
    class Meta:
        model = User
        fields = ['email', 'password']

class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['avatarUrl', 'name' , 'aboutMe']

user/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import JoinForm, LoginForm, ProfileForm
from .models import Profile as ProfileModel

User = get_user_model()

class Join(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        
        form = JoinForm()
        context = {
            'form': form,
        }
        return render(request, 'user/user_join.html', context)
    
    def post(self, request):
        form = JoinForm(request.POST)
        if form.is_valid():
            user = form.save()
            profile = ProfileModel.objects.create(user=user)
            return redirect('user:login')

        form.add_error(None,'양식을 확인해주세요.')
        context = {
            'form': form
        }
        return render(request, 'user/user_join.html', context)

### Login
class Login(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        
        form = LoginForm()
        context = {
            'form': form,
        }
        return render(request, 'user/user_login.html', context)
        
    def post(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        
        form = LoginForm(request, request.POST)
        if form.is_valid():
            email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=email, password=password) # True, False
            
            if user:
                login(request, user)
                return redirect('blog:list')
            
        form.add_error(None, '양식을 확인해주세요.')
        context = {
            'form': form
        }
        
        return render(request, 'user/user_login.html', context)


### Logout
class Logout(View):
    def get(self, request):
        logout(request)
        return redirect('blog:list')


class ChangePassWord(View):
    def get(self, request):
        form = PasswordChangeForm(request.user, request.POST)
        context = {
            'form': form
        }
        return render(request,'user/user_change_pw.html',context)
    def post(self, request):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('blog:list')
        
        form.add_error(None,'Error 발생')
        context = {
            'form': form
        }
        return render(request,'user/user_change_pw.html',context)


class ProfileUpdate(LoginRequiredMixin,View):
    Mixin : LoginRequiredMixin
    login_url = '/user/login'
    redirect_field_name = 'next'
    
    def get(self, request):
        profile = ProfileModel.objects.get(user=request.user.pk)
        form = ProfileForm(initial={'avatarUrl': profile.avatarUrl, 'name': profile.name , 'aboutMe': profile.aboutMe})
        context = {
            'form': form,
            'type': 'edit'
        }
        return render(request, 'user/user_profile.html', context)
        
    def post(self, request):
        
        user = User.objects.get(pk=request.user.pk)
        profile = ProfileModel.objects.get(user=user)
        name = request.POST['name']
        aboutMe = request.POST['aboutMe']
        
        try:
            avatarUrl = request.FILES['avatarUrl']
        except:
            profile.name = name
            profile.aboutMe = aboutMe
        else:
            profile.name = name
            profile.avatarUrl = avatarUrl
            profile.aboutMe = aboutMe
        
        profile.save()
        return redirect('blog:list')

user/templates/user/user_change_pw.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
    <form class="change-pw" action="{% url 'user:change-pw' %}" method="post">
        <h2>Change Password</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="change-btn" type="submit" value="변경">
    </form>
    <script src="{% static 'user/js/change-pw.js' %}"></script>
{% endblock %}

user/templates/user/user_join.html
<!DOCTYPE html>
<html lang="ko">
    {% load static %}
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>회원가입</title>
        <link rel="stylesheet" href="{% static 'blog/css/reset.css' %}" />
        <!-- font : pretendard -->
		<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />
		<link rel="stylesheet" href="{% static 'blog/css/global.css' %}" />

		<!-- component -->
		<link rel="stylesheet" href="{% static 'blog/css/button.css' %}" />

		<!-- user -->
		<link rel="stylesheet" href="{% static 'user/css/join.css' %}" />

    </head>
    <body>
        <main>
            <form class="user-join" action="{% url 'user:join' %}" method="post">
                <h2>JOIN</h2>
                {% csrf_token %}
                {{ form.as_p }}
                <input class="join_btn" type="submit" value="회원가입">
            </form>
        </main>
    </body>
    <script src="{% static 'user/js/join.js' %}"></script>
</html>

user/templates/user/user_login.html
<!DOCTYPE html>
<html lang="ko">
    {% load static %}
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>로그인</title>
        <link rel="stylesheet" href="{% static 'blog/css/reset.css' %}" />
        <!-- font : pretendard -->
		<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />
		<link rel="stylesheet" href="{% static 'blog/css/global.css' %}" />

		<!-- component -->
		<link rel="stylesheet" href="{% static 'blog/css/button.css' %}" />

		<!-- user -->
		<link rel="stylesheet" href="{% static 'user/css/login.css' %}" />

    </head>
    <body>
        <main>
    		<form class="user-login" action="{% url 'user:login' %}" method="post">
                <h2>LOGIN</h2>
                {% csrf_token %}
                {{ form.as_p }}
                <a href="{%url 'user:join' %}">회원가입 바로가기</a>
                <input class="login_btn" type="submit" value="로그인">
            </form>
        </main>
    </body>
    <script src="{% static 'user/js/login.js' %}"></script>
</html>

user/templates/user/user_profile.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
    {% if type != 'edit' %}
    <form class="user-profile-form" action="{% url 'user:pf-create' %}" enctype="multipart/form-data" method="post">
    {% else %}
    <form class="user-profile-form" action="{% url 'user:pf-edit' %}" enctype="multipart/form-data" method="post">
    {% endif %}
        <h2>Profile</h2>
        <h3>My Avatar</h3>
        {% if request.user.profile.avatarUrl %}
            <img src="{{request.user.profile.avatarUrl.url}}" alt="" class="user-avatar" />
        {% else %}
            <img src="{%static 'user/image/basic_profile.jpg'%}" alt="" class="user-avatar" />
        {% endif %}
        {% csrf_token %}
        <div class="avatar_div">
            <label for="profile-avatar">이미지 변경하기</label>
            <input type="file" id="profile-avatar" name="{{ form.avatarUrl.name }}" value="{{ form.initial.avatarUrl }}">
        </div>
        <div class="name_div">
            <label for="profile-name">닉네임</label>
            <input type="text" id="profile-name" name="{{ form.name.name }}" value="{{ form.initial.name }}">
        </div>
        <div class="aboutMe_div">
            <label for="profile-aboutMe">자기소개</label>
            <textarea id="profile-aboutMe"  name="{{ form.aboutMe.name }}" type="text" rows="20">{{ form.initial.aboutMe }}</textarea>
        </div>
        <input class="pf-save_btn" type="submit" value="저장">
        <a class="change-pw_btn" href="{% url 'user:change-pw' %}">비밀번호 변경 하러가기</a>
    </form>
    <script src="{% static 'user/js/profile.js' %}"></script>
{% endblock %}