App/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import IndexMain
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('',IndexMain.as_view(), name='home'),
    # re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # re_path(r'^staticfiles/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import Index, Write, Detail, Delete, Update, CommentWrite, CommentDelete, Search, ImgUpload, LoadPost, CategorySearch, Likepost

app_name = 'blog'

urlpatterns = [
    path('', Index.as_view() , name='list'),
    # post
    path('write/', Write.as_view() , name='write'),
    path('<int:pk>/', Detail.as_view() , name='detail'),
    path('edit/<int:pk>/', Update.as_view() , name='edit'),
    path('loadpost/<int:pk>/', LoadPost.as_view() , name='load'),
    path('delete/<int:pk>/', Delete.as_view() , name='delete'),
    path('search/', Search.as_view() , name='search'),
    path('categorysearch/', CategorySearch.as_view() , name='category'),
    path('imageupload/', ImgUpload.as_view() , name='img-upload'),
    path('like/<int:pk>/', Likepost.as_view() , name='like'),
    # comment
    path('comment/write/<int:pk>/', CommentWrite.as_view() , name='cm-write'),
    path('comment/delete/<int:pk>/', CommentDelete.as_view() , name='cm-delete'),

]

user/urls.py
from django.urls import path
from .views import Join, Login, Logout, ProfileUpdate, ChangePassWord

app_name = 'user'

urlpatterns = [
    path("join/", Join.as_view(), name='join'),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name='logout'),
    path("changePassword/", ChangePassWord.as_view(), name='change-pw'),
    path("profile/edit/", ProfileUpdate.as_view(), name='pf-edit'),
] 

templates/base.html
<!DOCTYPE html>
<html lang="ko">
    {% load static %}
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>블로그</title>
        <link rel="stylesheet" href="{% static 'blog/css/reset.css' %}" />
        <!-- font : pretendard -->
		<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />
		<link rel="stylesheet" href="{% static 'blog/css/global.css' %}" />
		<!-- fontawesome -->
		<link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"
        />
		<!-- layout -->
		<link rel="stylesheet" href="{% static 'blog/css/header.css' %}" />
		<link rel="stylesheet" href="{% static 'blog/css/footer.css' %}" />
		<link rel="stylesheet" href="{% static 'blog/css/about.css' %}" />

		<!-- component -->
		<link rel="stylesheet" href="{% static 'blog/css/button.css' %}" />
		<link rel="stylesheet" href="{% static 'blog/css/category.css' %}" />
		<link rel="stylesheet" href="{% static 'blog/css/author.css' %}" />

		<!-- blog -->
		<link rel="stylesheet" href="{% static 'blog/css/post.css' %}" />
		<link rel="stylesheet" href="{% static 'blog/css/posts.css' %}" />
		<link rel="stylesheet" href="{% static 'blog/css/main.css' %}" />
        <link rel="stylesheet" href="{% static 'blog/css/wrapbox.css' %}" />
		<link rel="stylesheet" href="{% static 'blog/css/view.css' %}" />
		<link rel="stylesheet" href="{% static 'blog/css/write.css' %}" />
		<link rel="stylesheet" href="{% static 'blog/css/comment.css' %}" />

		<!-- user -->
		<link rel="stylesheet" href="{% static 'user/css/profile.css' %}" />
		<link rel="stylesheet" href="{% static 'user/css/change-pw.css' %}" />
		
    </head>
    <body>
        <!-- header -->
		<header>
			<div class="max-width">
				<h1>
					<a href="{% url 'blog:list' %}">
						<img src="{% static 'blog/assets/Logo.svg' %}" alt="My Blog" />
					</a>
				</h1>
				<ul>
                    {% if request.user.is_authenticated %}
					<!-- 로그인 -->
					<li>
						<a href="{% url 'blog:write' %}" class="button">
							<img src="{% static 'blog/assets/icon-modify-white.svg' %}" alt="" />
							<span>Write</span>
						</a>
					</li>
					<li>
						<a href="{%url 'user:logout' %}" class="button gray">
							<img src="{% static 'blog/assets/icon-logout.svg' %}" alt="" />
							<span>Logout</span>
						</a>
					</li>
					<li class="profile-img">
						<a href="{%url 'user:pf-edit' %}">
							{% if request.user.profile.avatarUrl %}
								<img src="{{request.user.profile.avatarUrl.url}}" alt="" class="user-profile" />
							{% else %}
								<img src="{%static 'user/image/basic_profile.jpg'%}" alt="" class="user-profile" />
							{% endif %}
						</a>
					</li>
					<!-- //로그인 -->
                    {% else %}
					<!-- 로그아웃 -->
					<li>
						<a href="{%url 'user:login' %}" class="button gray">
							<img src="{% static 'blog/assets/icon-login.svg' %}" alt="" />
							<span>Login</span>
						</a>
					</li>
					<li class="only-pc">
						<a href="{%url 'user:join' %}" class="button gray">
							<img src="{% static 'blog/assets/icon-register.svg' %}" alt="" />
							<span>join</span>
						</a>
					</li>
					<!--// 로그아웃 -->
                    {% endif %}
				</ul>
			</div>
		</header>
		<!--// header -->
        <main class="container">
            {% block content %} 
            {% endblock %}
        </main>
        <!-- footer -->
		<footer>
			<div class="max-width">
				<h2>Copyright 2023. Chilli All rights reserved.</h2>
			</div>
		</footer>
		<!-- //footer -->
		
    </body>
</html>
   

templates/index.html
<!DOCTYPE html>
<html lang="ko">
    {% load static %}
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Home</title>
        <link rel="stylesheet" href="{% static 'blog/css/reset.css' %}" />
        <link rel="stylesheet" href="{% static 'main/css/index.css' %}" />
    </head>
    <body>
        <main class="container">
            <h1 class="main_title">
                <p>블로그에</p>
                <p>찾아와주셔서 감사합니다 :)</p>
            </h1>
            <a class="main_link" href="{% url 'blog:list' %}">블로그 바로가기</a>
        </main>
    </body>
</html>
   